# Kodkalender 2021

## Lucka 1
### Del 1

In [2]:
def läsin_fil(fil):
    
    with open(fil, "r") as f:
        text = f.readlines()

    return text
    
sökväg = "files/exempel 1.txt"
#sökväg = "files/input 1.txt"

lista_mätvärden = [int(l.strip()) for l in läsin_fil(sökväg)]

antal_ökande = sum([mv - lista_mätvärden[i] > 0 for i, mv in enumerate(lista_mätvärden[1:])])

print(f"Antal mätvärden med högre värde än föregående: {antal_ökande}")

Antal mätvärden med högre värde än föregående: 7


### Del 2

In [3]:
antal_ökande_tripletter = sum([mv - lista_mätvärden[i] > 0 for i,mv in enumerate(lista_mätvärden[3:])])

print(f"Antal tripletter med högre värde än föregående: {antal_ökande_tripletter}")


Antal tripletter med högre värde än föregående: 5


## Lucka 2
### Del 1


In [4]:
sökväg = "files/exempel 2.txt"
#sökväg = "files/input 2.txt"

text = läsin_fil(sökväg)
kommandon =[l.split() for l in text]

framåt = sum([(int(k[1]) if k[0] == "forward" else 0)  for k in kommandon])
djup = sum([(-int(k[1]) if k[0] == "up" else int(k[1]) if k[0] == "down" else 0)  for k in kommandon])

print(f"Produkten av position framåt och djup: {framåt * djup}")

Produkten av position framåt och djup: 150


### Del 2

In [5]:
framåt_sum, djup, sikte = 0, 0, 0

for kom in kommandon:
    framåt=0
    kommando, kommando_värde =kom[0], int(kom[1])
    
    if kommando == "forward":
        framåt=kommando_värde
        framåt_sum += framåt 

    elif kommando == "down":
        sikte += kommando_värde
        
    elif kommando == "up":
        sikte -= kommando_värde
    
    djup += sikte * framåt

print(f"Produkten av position framåt och djup: {framåt_sum * djup}")

Produkten av position framåt och djup: 900


## Lucka 3
### Del 1


In [6]:
sökväg = "files/exempel 3.txt"
#sökväg = "files/input 3.txt"

text = läsin_fil(sökväg)
diagnosrapport =[l.split() for l in text]

antal_siffror = len(diagnosrapport[0][0])
antal_rader = len(diagnosrapport)
γ,ε = 0, 0

for i in range (antal_siffror):       
    vanligaste_siffra = round(sum([int(diagnosrapport[j][0][i]) for j in range(antal_rader)])/antal_rader) # Vad ska hända om det är lika? Här kommer 1 prioriteras.

    γ += vanligaste_siffra * 10**(antal_siffror-1-i)
    ε += (1 - vanligaste_siffra) * 10**(antal_siffror-1-i)

energiförbrukning = int(str(ε),base=2)*int(str(γ),base=2)

print(f"Energiförbrukningen är {energiförbrukning}")


Energiförbrukningen är 198


### Del 2

In [7]:
def utvärdering(rapport, prioriterad_siffra ):
    """Utvärderar diagnosrapporten med avseende på vilken siffra som ska prioriteras 
    och väljer ut det enskilda värde uppfyller kriterierna"""
    
    kvarvarande_rader = rapport
    antal_siffror = len(rapport[0][0])

    for i in range (antal_siffror):       
        antal_rader = len(kvarvarande_rader)
        if antal_rader == 1: break

        antal_ettor = sum([int(kvarvarande_rader[j][0][i]) for j in range(antal_rader)])
        antal_nollor = antal_rader - antal_ettor
        
        if  antal_ettor > antal_nollor:
            siffra_att_behålla = prioriterad_siffra
        elif antal_nollor > antal_ettor:
            siffra_att_behålla = 1 - prioriterad_siffra
        else:
            siffra_att_behålla = prioriterad_siffra

        rader_att_spara = []
        for rad in kvarvarande_rader:
            if int(rad[0][i])== siffra_att_behålla:
                rader_att_spara.append(rad)

        kvarvarande_rader = rader_att_spara        
    
    return int(kvarvarande_rader[0][0], 2)

syre_generering = utvärdering(diagnosrapport, 1)
co2_rening = utvärdering(diagnosrapport, 0)
liv = syre_generering * co2_rening

print(f"Livsupppehållande systemen har nivå: {liv}")

Livsupppehållande systemen har nivå: 230


## Lucka 4
### Del 1


In [8]:
import numpy as np

sökväg = "files/exempel 4.txt"
#sökväg = "files/input 4.txt"

def skapa_brickor(text):

    längd_sida_bricka = 5
    brickor = np.zeros(((len(text) - 1) // (längd_sida_bricka + 1), längd_sida_bricka, längd_sida_bricka) , np.int16)
    brick_index = 0

    for rad, text_rad in enumerate(text[2:]): 
        if text_rad:
            for kol, text_kol in enumerate(text_rad.split()):
                brickor[brick_index, rad % 6, kol]  = int(text_kol)

        brick_index = (rad + 1) // 6
    return brickor

def kryssa_bricka():

    tal_index = np.where(bingobrickor==nr)
  
    for i, v in enumerate(tal_index[0]):
        if v in vinnande_brickor:
            continue
        
        bingobrickor[tal_index[0][i], tal_index[1][i], tal_index[2][i]] = -1
        
        if bingobrickor[tal_index[0][i], tal_index[1][i], :].sum() == -5 or bingobrickor[tal_index[0][i], :, tal_index[2][i]].sum() == -5:
            vinnande_brickor.append(tal_index[0][i]) 
            vinnande_nummer.append(nr)


def poängräkning():

    summa_kvarvarande_tal = np.where(bingobrickor[vinnande_brickor[-1]] >= 0, bingobrickor[vinnande_brickor[-1]], 0).sum()
    slutgiltig_poäng = summa_kvarvarande_tal * vinnande_nummer[-1]
    
    print(F"Summan av kvarvarande nummer på bingobrickan: {summa_kvarvarande_tal}. Sita dragna numret: {vinnande_nummer[-1]}")
    print(f"Den slutliga poängen är: {slutgiltig_poäng}")           


text = läsin_fil(sökväg)
dragningslista = eval(text[0]) 
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:

    kryssa_bricka()
    
    if vinnande_brickor:
        print("Bingo!\n")
        break
 
if len(vinnande_brickor) > 1:
    print("Flera brickor har Bingo!\n")
    print(vinnande_brickor)

poängräkning()

Bingo!

Summan av kvarvarande nummer på bingobrickan: 188. Sita dragna numret: 24
Den slutliga poängen är: 4512


### Del 2

In [9]:
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:
    
    kryssa_bricka()
    
    if len(vinnande_brickor) == len(bingobrickor):
        break

poängräkning()

Summan av kvarvarande nummer på bingobrickan: 148. Sita dragna numret: 13
Den slutliga poängen är: 1924


## Lucka 5
### Del 1


In [10]:
def farliga_positioner(karta):
    antal_farliga_positioner = len(np.where(karta>= 2)[0])
    print(f"Antalet farliga positioner är: {antal_farliga_positioner}")


In [11]:
sökväg = "files/exempel 5.txt"
#sökväg = "files/input 5.txt"

text = läsin_fil(sökväg)

linjer_koordinater = np.array([eval(rad.replace(" -> ",',')) for rad in text])
y_dim, x_dim = linjer_koordinater[:, (0, 2)].max() + 1, linjer_koordinater[:, (1, 3)].max() + 1

karta = np.zeros((y_dim, x_dim), np.int8)

In [12]:
for linje in linjer_koordinater:
    if linje[0] == linje [2] or linje[1] == linje [3]:
        
        y =sorted((linje[0],linje[2]))
        x =sorted((linje[1],linje[3]))

        karta[y[0]: y[1]+1, x[0]: x[1]+1] += 1

farliga_positioner(karta)

Antalet farliga positioner är: 5


### Del 2

In [13]:
for linje in linjer_koordinater:

    y =((linje[0],linje[2]))
    x =((linje[1],linje[3]))

    if y[1] - y[0] >= 0 :
        y2 =[yi for yi in range(y[0], y[1] + 1, 1)]
    else:
        y2 =[yi for yi in range(y[0], y[1] - 1, -1)]

    if x[1] - x[0] >= 0:
        x2 =[xi for xi in range(x[0], x[1] +1, 1)]
    else:
        x2 =[xi for xi in range(x[0] ,x[1] - 1, -1)]

    if len(y2) == len(x2):
        for yi, xi in zip(y2, x2):
            karta[yi, xi] += 1 

print(karta.transpose()) 

farliga_positioner(karta)

[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]
Antalet farliga positioner är: 12


## Lucka 6
### Del 1


In [14]:
#Långsam och minneskrävande lösning :(

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80

alla_fiskar = np.array(eval(läsin_fil(sökväg)[0]))

for i in range(antal_dagar):
    #print(i)
    alla_fiskar -= 1
    nya_fiskar = np.where(alla_fiskar == -1)[0]
    
    alla_fiskar[nya_fiskar] = 6
    alla_fiskar = np.append(alla_fiskar, [8 for _ in range(nya_fiskar.size)])

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.size} st.")

Antalet fiskar efter 80 dagar är 5934 st.


### Del 2

In [15]:
# Betydligt effektivare lösning :D

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80
#antal_dagar = 256

fiskar_vid_dag_0 = np.array(eval(läsin_fil(sökväg)[0]))
alla_fiskar = np.array([(fiskar_vid_dag_0 == i).sum()  for i in range (9)], np.int64)

for i in range(antal_dagar):

    alla_fiskar = np.roll(alla_fiskar, -1)
    alla_fiskar[6] += alla_fiskar[8]

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.sum()} st.")

Antalet fiskar efter 80 dagar är 5934 st.


## Lucka 7
### Del 1


In [16]:
sökväg = "files/exempel 7.txt"
sökväg = "files/input 7.txt"

krabbor_position = np.array(eval(läsin_fil(sökväg)[0]))
intervall_positioner = range(krabbor_position.min(), krabbor_position.max() + 1)

In [17]:
lägsta_bränsleförbrukning = min([np.absolute(krabbor_position - p).sum() for p in intervall_positioner])
print(f"Den lägta bränsleförbrukningen är {lägsta_bränsleförbrukning}")

Den lägta bränsleförbrukningen är 348664


### Del 2

In [18]:
lägsta_bränsleförbrukning = min([sum([(i**2+i)/2 for i in (np.absolute(krabbor_position - p))]) for p in intervall_positioner]) 

print(f"Den lägta bränsleförbrukningen är {lägsta_bränsleförbrukning}")

Den lägta bränsleförbrukningen är 100220525.0


In [19]:
# Smaratare sätt är att bara räkna ut bränsleförbrukningen för positionerna närmast medelvärdet.
np.floor(krabbor_position.mean()), np.ceil(krabbor_position.mean())

(479.0, 480.0)

## Lucka 8
### Del 1


In [20]:
sökväg = "files/exempel 8.txt"
#sökväg = "files/input 8.txt"

text = läsin_fil(sökväg)
text = [ text[i].strip() + " " + text[i+1]  for i in range(0, len(text), 2)] # Endast för exempeldata med radbrytning
data = [rad.split(" ") for rad in text]

In [21]:
# Alternativ lösning 1
antal_siffror = 0
for rad in data:
    for siffra in rad[11:]:
        antal_segment = len(siffra.strip())
        if 2 <= antal_segment <= 4 or antal_segment == 7:
            antal_siffror += 1
           
print(f"Antalet siffror (1, 4, 7, 8) är: {antal_siffror}")

Antalet siffror (1, 4, 7, 8) är: 26


In [22]:
# Alternativ lösning 2
antal_siffror = sum([sum([(1 if 2 <= len(siffra.strip()) <= 4 or len(siffra.strip()) ==7 else 0) for siffra in rad[11:]]) for rad in data])

print(f"Antalet siffror (1, 4, 7, 8) är: {antal_siffror}")

Antalet siffror (1, 4, 7, 8) är: 26


### Del 2

Vilken röra...

In [23]:
def hitta_låga_ingångar(display_siffra):
    """Hitta de rader i kopplingschemat som motsvarare bokstäver som inte förekommer i strängen."""

    ingångar = [i for i in  range (7)]
    for bokstav in display_siffra:
        ingångar[ord(bokstav) - ord('a')] = -1
    ingångar = list(set(ingångar))
    ingångar.sort()
    ingångar.pop(0)
    return ingångar          

In [24]:
segment_per_siffra = {  (0, 1, 2, 4, 5, 6)      : 0,
                        (2, 5)                  : 1,
                        (0, 2, 3, 4, 6)         : 2,
                        (0, 2, 3, 5, 6)         : 3,
                        (1, 2, 3, 5)            : 4,
                        (0, 1, 3, 5, 6)         : 5,
                        (0, 1, 3, 4, 5, 6)      : 6,
                        (0, 2, 5)               : 7,
                        (0, 1, 2, 3, 4, 5, 6)   : 8,
                        (0, 1, 2, 3, 5, 6)      : 9
}

total_summa = 0

for display_i in data:
    kopplingsschema = np.ones((7, 7))

    # Kopplingar som kan uteslutas direkt beroende på antal segment aktiva
    for display_siffra_j in display_i:
        display_siffra_j = display_siffra_j.strip()
       
        antal_segment = len(display_siffra_j)
        
        if antal_segment == 2:
            segment = (2, 5)
            aktiv_lista = True 
                   
        elif antal_segment == 3:
            segment = (0, 2, 5)
            aktiv_lista = True  

        elif antal_segment == 4:
            segment = (1, 2, 3, 5)
            aktiv_lista = True  

        elif antal_segment == 5:
            segment = (1, 2, 4, 5)
            aktiv_lista = False 

        elif antal_segment == 6:
            segment = (2, 3, 4)
            aktiv_lista = False
        else:
            continue

        if aktiv_lista:
            for ingång in display_siffra_j:
                ingång_index = ord(ingång)-ord('a')
            
                for k in range(7):
                    if not k in segment:
                        kopplingsschema[ingång_index, k] = 0  
                    

        låga_ingångar =hitta_låga_ingångar(display_siffra_j)

        for rad in låga_ingångar:
            for k in range(7):
                if (k in segment and aktiv_lista) or (not k in segment and not aktiv_lista):
                    kopplingsschema[rad, k] = 0
                    

    kopplingsschema_o = 0 
    while not (kopplingsschema == kopplingsschema_o).all():
        kopplingsschema_o = kopplingsschema
        
        for display_siffra_k in display_i:
            display_siffra_k = display_siffra_k.strip()
            antal_segment = len(display_siffra_k)
            
            if antal_segment == 5:

                låga_ingångar =hitta_låga_ingångar(display_siffra_k)
            
                for j, ingång_j in enumerate(låga_ingångar):
                    if kopplingsschema[ingång_j, 2] == 0 and kopplingsschema[ingång_j, 4] == 0:
                        kopplingsschema[låga_ingångar[1-j], 2] = 0  
        
                    if kopplingsschema[ingång_j, 1] == 0 and kopplingsschema[ingång_j, 5] == 0:
                        kopplingsschema[låga_ingångar[1-j], 5] = 0  
                   
        # Sudoku rensa kol omm endast 1 etta på rad  
        for j, ingång_j in enumerate(kopplingsschema):
            if ingång_j.sum() == 1:
                index = np.where(ingång_j == 1)[0][0]
                kopplingsschema[:,index] = 0 
                kopplingsschema[j, index ] = 1 

    # Omvandla indata till siffror
    siffror = ""
    for display_siffra_l in display_i[-4:]:
        display_siffra_l = display_siffra_l.strip()

        aktiva_segment =[ np.where(kopplingsschema[ ord(tecken) - ord('a')])[0][0] for tecken in display_siffra_l]
        aktiva_segment.sort()

        siffror += str(segment_per_siffra[tuple(aktiva_segment)])

    total_summa += int(siffror)

print(f"Den totala summan av talen på displayerna är {total_summa}")    

Den totala summan av talen på displayerna är 61229


## Lucka 9
### Del 1


In [25]:
sökväg = "files/exempel 9.txt"
#sökväg = "files/input 9.txt"

text = läsin_fil(sökväg)

karta = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])
karta_inramad = np.ones(np.array(karta.shape)+2, np.int16) *10
karta_inramad[1:-1, 1:-1] = karta

In [26]:
# Hitta den här på nätet :-) Ändrade dock från <= til <
def local_minima(array2d):
    return ((array2d < np.roll(array2d,  1, 0)) &
            (array2d < np.roll(array2d, -1, 0)) &
            (array2d < np.roll(array2d,  1, 1)) &
            (array2d < np.roll(array2d, -1, 1)))


In [27]:
bool_array = local_minima(karta_inramad)[1:-1, 1:-1]      
svar = (bool_array * (karta + 1)).sum()
print(f"Summan av risknivåerna för kartans minpunkter är {svar}" )

Summan av risknivåerna för kartans minpunkter är 15


### Del 2

In [28]:
minpunkter = np.where(bool_array)
bassängstorlekar = []

for rad, kol in zip(minpunkter[0]+1, minpunkter[1]+1):

    bassäng = np.array(np.zeros(karta_inramad.shape), np.bool8)

    bassäng[rad, kol] = True

    punkter_att_kontrollera = [(rad, kol)] 

    while punkter_att_kontrollera:
        (rad, kol) = punkter_att_kontrollera.pop()
        
        närliggande_punkter = [(rad - 1, kol), (rad + 1, kol), (rad, kol - 1), (rad, kol + 1)]
        for närliggande_punkt in närliggande_punkter:

            if not bassäng[närliggande_punkt] and karta_inramad[närliggande_punkt] < 9:
                bassäng[närliggande_punkt] = True
                punkter_att_kontrollera.append(närliggande_punkt)

    bassängstorlekar.append(bassäng.sum())

bassängstorlekar.sort()
svar = np.array(bassängstorlekar[-3:]).prod()

print(f"Produkten av arean av de tre största bassängerna är {svar}.")

Produkten av arean av de tre största bassängerna är 1134.


## Lucka 10
### Del 1


In [29]:
# Inläsning av indata
sökväg = "files/exempel 10.txt"
#sökväg = "files/input 10.txt"

text = läsin_fil(sökväg) 

# Nödvändiga data gemensammt del 1 och del 2
möjliga_startparenteser = ('(', '[', '{', '<')
möjliga_slutparenteser = {')' : '(', ']' : '[', '}' : '{', '>' : '<'}

text


['[({(<(())[]>[[{[]{<()<>>\n',
 '[(()[<>])]({[<{<<[]>>(\n',
 '{([(<{}[<>[]}>{[]{[(<()>\n',
 '(((({<>}<{<{<>}{[]{[]{}\n',
 '[[<[([]))<([[{}[[()]]]\n',
 '[{[{({}]{}}([{[{{{}}([]\n',
 '{<[[]]>}<{[{[{[]{()[[[]\n',
 '[<(<(<(<{}))><([]([]()\n',
 '<{([([[(<>()){}]>(<<{{\n',
 '<{([{{}}[<[[[<>{}]]]>[]]\n']

In [30]:
# Nödvändig data
poäng_felaktiga_parenteser = {')' : 3, ']' : 57, '}' : 1197, '>' : 25137}

# Loopa igenom varje rad och tecken i indatan
totalpoäng = 0
for rad in text:
    startparenteser = []
    for tecken in rad.strip():
        
        # Kontrollera vilken typ av tecken 
        if tecken in möjliga_startparenteser:                       # tecken är en startparentes
            startparenteser.append(tecken)                          # Spara öppningsparentes i lista
        elif möjliga_slutparenteser[tecken] == startparenteser[-1]: # tecken är matchar senaste startparentes
            startparenteser.pop()                                   # Avlägsna matchad parentes ur lista
        else:                      
            totalpoäng += poäng_felaktiga_parenteser[tecken]        # Addera poäng för upptäckt felaktighet
            break                                                   # Byt till nästa rad 

print(f"Den totala poängen för ogiltiga tecken är {totalpoäng}")        

Den totala poängen för ogiltiga tecken är 26397


### Del 2

In [31]:
# Nödvändig data
poäng_saknade_parenteser = {'(' : 1, '[' : 2, '{' : 3, '<' : 4}

# Loopa igenom varje rad i indata
poäng_per_godkänd_rad = []
for rad in text:
    
    # Loopa igenom alla tecken i aktuell rad
    startparenteser = []
    for tecken in rad:
        
        # Kontrollera vilken typ av tecken 
        if tecken in möjliga_startparenteser:                           # tecken är en startparentes
            startparenteser.append(tecken)                              # Spara öppningsparentes i lista
        elif tecken in möjliga_slutparenteser:                          # Kontrollera om tecken är en slutparentes
            if möjliga_slutparenteser[tecken] == startparenteser[-1]:   # tecken är matchar senaste startparentes
                startparenteser.pop()                                   # Avlägsna matchad parentes ur lista
            else:                                                       # Annars är tecken == '\n' -> ny rad    
                break                                                   # Byt till nästa rad                                                

    # Beräkna poäng om giltig rad
    if tecken == '\n': 
        poäng = 0
        for p in reversed(startparenteser): # Tilldela en slutparentes till alla öppna parenteser i rätt ordning
            poäng *= 5
            poäng += poäng_saknade_parenteser[p]

        poäng_per_godkänd_rad.append(poäng)

# Hitta värdet som ligger i mitten
poäng_per_godkänd_rad.sort()
mitten_index = len(poäng_per_godkänd_rad)// 2

print(f"Den mittersta poängen i autofyll-tävlingen är {poäng_per_godkänd_rad[mitten_index]}")  

Den mittersta poängen i autofyll-tävlingen är 288957


## Lucka 11
### Del 1


In [104]:
# Inläsning av indata
sökväg = "files/exempel 11.txt"
#sökväg = "files/input 11.txt"

text = läsin_fil(sökväg) 

text

['5483143223\n',
 '2745854711\n',
 '5264556173\n',
 '6141336146\n',
 '6357385478\n',
 '4167524645\n',
 '2176841721\n',
 '6882881134\n',
 '4846848554\n',
 '5283751526\n']

In [105]:
def dumbo_flash(rad, kol):
    """Blinkand dumbobläckfisk
    Triggar angränsande bläckfiskar.
    Ange position i nätverket"""   
    
    # Alla omgivande punkter
    närliggande_punkter = [(rad - 1, kol), (rad + 1, kol), (rad, kol - 1), (rad, kol + 1), (rad - 1, kol - 1), (rad + 1, kol -1), (rad - 1, kol + 1), (rad + 1, kol + 1)]

    for (r, k) in närliggande_punkter:
        
        # Kontrollera att punkten inte ligger utanför nätverk
        if not 0 <= r < dumbo_grid.shape[0] or not 0 <= k < dumbo_grid.shape[1]: 
            continue

        # Öka energinivå i punkten 
        dumbo_grid[r, k] += 1 

        # Kontrollera om punkten blinkar
        if dumbo_grid[r, k] == kritisk_energinivå + 1:   # Om högre -> har redan blinkat
            dumbo_flash(r, k)


In [106]:
# Konstanter
antal_tidssteg = 100
kritisk_energinivå =9

# Skapa grid med bläckfiskar
dumbo_grid = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])

print("Utgångsläge\n", dumbo_grid)

totalt_antal_ljusblinkningar = 0


# Loopa genom alla tidssteg
for tids_steg in range(antal_tidssteg):
    
    # Öka engerginivån hos alla bläckfiskar   
    dumbo_grid += 1

    # Blinka lilla bläckfisk där...
    rader, kollonner = np.where(dumbo_grid > kritisk_energinivå)
    for rad, kol in zip(rader, kollonner):
        dumbo_flash(rad, kol)

    # Nollställ energinivån hos alla bläckfiskar som blinkat
    dumbo_grid[dumbo_grid > kritisk_energinivå] = 0

    # Räkna poäng
    totalt_antal_ljusblinkningar += dumbo_grid.size - np.count_nonzero(dumbo_grid)

print(f"Det totala antalet ljusblinkningar efter {antal_tidssteg} steg är {totalt_antal_ljusblinkningar}.")

Utgångsläge
 [[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
Det totala antalet ljusblinkningar efter 100 steg är 1656.


### Del 2

In [107]:
# Konstanter
kritisk_energinivå =9

# Skapa grid med bläckfiskar
dumbo_grid = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])

print("Utgångsläge\n", dumbo_grid)

# Loopa genom tills alla bläckfiskar blinkar synkront
antal_steg = 0
while dumbo_grid.sum() != 0:
    antal_steg += 1

    # Öka engerginivån hos alla bläckfiskar   
    dumbo_grid += 1

    # Blinka lilla bläckfisk där...
    rader, kollonner = np.where(dumbo_grid > kritisk_energinivå)
    for rad, kol in zip(rader, kollonner):
        dumbo_flash(rad, kol)

    # Nollställ energinivån hos alla bläckfiskar som blinkat
    dumbo_grid[dumbo_grid > kritisk_energinivå] = 0
   
print("\nEfter sista steget\n", dumbo_grid)
print(f"\nDet totala antalet steg tills alla bläckfiskar blinkar synkront är {antal_steg}.")

Utgångsläge
 [[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]

Efter sista steget
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Det totala antalet steg tills alla bläckfiskar blinkar synkront är 195.


## Lucka 12
### Del 1


### Del 2

## Lucka 13
### Del 1


### Del 2

## Lucka 14
### Del 1


### Del 2

## Lucka 15
### Del 1


### Del 2

## Lucka 16
### Del 1


### Del 2

## Lucka 17
### Del 1


### Del 2

## Lucka 18
### Del 1


### Del 2

## Lucka 19
### Del 1


### Del 2

## Lucka 20
### Del 1


### Del 2

## Lucka 21
### Del 1


### Del 2

## Lucka 22
### Del 1


### Del 2

## Lucka 23
### Del 1


### Del 2

## Lucka 24
### Del 1


### Del 2

## Lucka 25
### Del 1


### Del 2