# Kodkalender 2021

## Lucka 1
### Del 1

In [1]:
def läsin_fil(fil):
    
    with open(fil, "r") as f:
        text = f.readlines()

    return text
    
sökväg = "files/exempel 1.txt"
#sökväg = "files/input 1.txt"

lista_mätvärden = [int(l.strip()) for l in läsin_fil(sökväg)]

antal_ökande = sum([mv - lista_mätvärden[i] > 0 for i, mv in enumerate(lista_mätvärden[1:])])

print(f"Antal mätvärden med högre värde än föregående: {antal_ökande}")

Antal mätvärden med högre värde än föregående: 7


### Del 2

In [2]:
antal_ökande_tripletter = sum([mv - lista_mätvärden[i] > 0 for i,mv in enumerate(lista_mätvärden[3:])])

print(f"Antal tripletter med högre värde än föregående: {antal_ökande_tripletter}")


Antal tripletter med högre värde än föregående: 5


## Lucka 2
### Del 1


In [3]:
sökväg = "files/exempel 2.txt"
#sökväg = "files/input 2.txt"

text = läsin_fil(sökväg)
kommandon =[l.split() for l in text]

framåt = sum([(int(k[1]) if k[0] == "forward" else 0)  for k in kommandon])
djup = sum([(-int(k[1]) if k[0] == "up" else int(k[1]) if k[0] == "down" else 0)  for k in kommandon])

print(f"Produkten av position framåt och djup: {framåt * djup}")

Produkten av position framåt och djup: 150


### Del 2

In [4]:
framåt_sum, djup, sikte = 0, 0, 0

for kom in kommandon:
    framåt=0
    kommando, kommando_värde =kom[0], int(kom[1])
    
    if kommando == "forward":
        framåt=kommando_värde
        framåt_sum += framåt 

    elif kommando == "down":
        sikte += kommando_värde
        
    elif kommando == "up":
        sikte -= kommando_värde
    
    djup += sikte * framåt

print(f"Produkten av position framåt och djup: {framåt_sum * djup}")

Produkten av position framåt och djup: 900


## Lucka 3
### Del 1


In [5]:
sökväg = "files/exempel 3.txt"
#sökväg = "files/input 3.txt"

text = läsin_fil(sökväg)
diagnosrapport =[l.split() for l in text]

antal_siffror = len(diagnosrapport[0][0])
antal_rader = len(diagnosrapport)
γ,ε = 0, 0

for i in range (antal_siffror):       
    vanligaste_siffra = round(sum([int(diagnosrapport[j][0][i]) for j in range(antal_rader)])/antal_rader) # Vad ska hända om det är lika? Här kommer 1 prioriteras.

    γ += vanligaste_siffra * 10**(antal_siffror-1-i)
    ε += (1 - vanligaste_siffra) * 10**(antal_siffror-1-i)

energiförbrukning = int(str(ε),base=2)*int(str(γ),base=2)

print(f"Energiförbrukningen är {energiförbrukning}")


Energiförbrukningen är 198


### Del 2

In [6]:
def utvärdering(rapport, prioriterad_siffra ):
    """Utvärderar diagnosrapporten med avseende på vilken siffra som ska prioriteras 
    och väljer ut det enskilda värde uppfyller kriterierna"""
    
    kvarvarande_rader = rapport
    antal_siffror = len(rapport[0][0])

    for i in range (antal_siffror):       
        antal_rader = len(kvarvarande_rader)
        if antal_rader == 1: break

        antal_ettor = sum([int(kvarvarande_rader[j][0][i]) for j in range(antal_rader)])
        antal_nollor = antal_rader - antal_ettor
        
        if  antal_ettor > antal_nollor:
            siffra_att_behålla = prioriterad_siffra
        elif antal_nollor > antal_ettor:
            siffra_att_behålla = 1 - prioriterad_siffra
        else:
            siffra_att_behålla = prioriterad_siffra

        rader_att_spara = []
        for rad in kvarvarande_rader:
            if int(rad[0][i])== siffra_att_behålla:
                rader_att_spara.append(rad)

        kvarvarande_rader = rader_att_spara        
    
    return int(kvarvarande_rader[0][0], 2)

syre_generering = utvärdering(diagnosrapport, 1)
co2_rening = utvärdering(diagnosrapport, 0)
liv = syre_generering * co2_rening

print(f"Livsupppehållande systemen har nivå: {liv}")

Livsupppehållande systemen har nivå: 230


## Lucka 4
### Del 1


In [7]:
import numpy as np

sökväg = "files/exempel 4.txt"
#sökväg = "files/input 4.txt"

def skapa_brickor(text):

    längd_sida_bricka = 5
    brickor = np.zeros(((len(text) - 1) // (längd_sida_bricka + 1), längd_sida_bricka, längd_sida_bricka) , np.int16)
    brick_index = 0

    for rad, text_rad in enumerate(text[2:]): 
        if text_rad:
            for kol, text_kol in enumerate(text_rad.split()):
                brickor[brick_index, rad % 6, kol]  = int(text_kol)

        brick_index = (rad + 1) // 6
    return brickor

def kryssa_bricka():

    tal_index = np.where(bingobrickor==nr)
  
    for i, v in enumerate(tal_index[0]):
        if v in vinnande_brickor:
            continue
        
        bingobrickor[tal_index[0][i], tal_index[1][i], tal_index[2][i]] = -1
        
        if bingobrickor[tal_index[0][i], tal_index[1][i], :].sum() == -5 or bingobrickor[tal_index[0][i], :, tal_index[2][i]].sum() == -5:
            vinnande_brickor.append(tal_index[0][i]) 
            vinnande_nummer.append(nr)


def poängräkning():

    summa_kvarvarande_tal = np.where(bingobrickor[vinnande_brickor[-1]] >= 0, bingobrickor[vinnande_brickor[-1]], 0).sum()
    slutgiltig_poäng = summa_kvarvarande_tal * vinnande_nummer[-1]
    
    print(F"Summan av kvarvarande nummer på bingobrickan: {summa_kvarvarande_tal}. Sita dragna numret: {vinnande_nummer[-1]}")
    print(f"Den slutliga poängen är: {slutgiltig_poäng}")           


text = läsin_fil(sökväg)
dragningslista = eval(text[0]) 
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:

    kryssa_bricka()
    
    if vinnande_brickor:
        print("Bingo!\n")
        break
 
if len(vinnande_brickor) > 1:
    print("Flera brickor har Bingo!\n")
    print(vinnande_brickor)

poängräkning()

Bingo!

Summan av kvarvarande nummer på bingobrickan: 188. Sita dragna numret: 24
Den slutliga poängen är: 4512


### Del 2

In [8]:
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:
    
    kryssa_bricka()
    
    if len(vinnande_brickor) == len(bingobrickor):
        break

poängräkning()

Summan av kvarvarande nummer på bingobrickan: 148. Sita dragna numret: 13
Den slutliga poängen är: 1924


## Lucka 5
### Del 1


In [9]:
def farliga_positioner(karta):
    antal_farliga_positioner = len(np.where(karta>= 2)[0])
    print(f"Antalet farliga positioner är: {antal_farliga_positioner}")


In [10]:
sökväg = "files/exempel 5.txt"
#sökväg = "files/input 5.txt"

text = läsin_fil(sökväg)

linjer_koordinater = np.array([eval(rad.replace(" -> ",',')) for rad in text])
y_dim, x_dim = linjer_koordinater[:, (0, 2)].max() + 1, linjer_koordinater[:, (1, 3)].max() + 1

karta = np.zeros((y_dim, x_dim), np.int8)

In [11]:
for linje in linjer_koordinater:
    if linje[0] == linje [2] or linje[1] == linje [3]:
        
        y =sorted((linje[0],linje[2]))
        x =sorted((linje[1],linje[3]))

        karta[y[0]: y[1]+1, x[0]: x[1]+1] += 1

farliga_positioner(karta)

Antalet farliga positioner är: 5


### Del 2

In [12]:
for linje in linjer_koordinater:

    y =((linje[0],linje[2]))
    x =((linje[1],linje[3]))

    if y[1] - y[0] >= 0 :
        y2 =[yi for yi in range(y[0], y[1] + 1, 1)]
    else:
        y2 =[yi for yi in range(y[0], y[1] - 1, -1)]

    if x[1] - x[0] >= 0:
        x2 =[xi for xi in range(x[0], x[1] +1, 1)]
    else:
        x2 =[xi for xi in range(x[0] ,x[1] - 1, -1)]

    if len(y2) == len(x2):
        for yi, xi in zip(y2, x2):
            karta[yi, xi] += 1 

print(karta.transpose()) 

farliga_positioner(karta)

[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]
Antalet farliga positioner är: 12


## Lucka 6
### Del 1


In [13]:
#Långsam och minneskrävande lösning :(

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80

alla_fiskar = np.array(eval(läsin_fil(sökväg)[0]))

for i in range(antal_dagar):
    #print(i)
    alla_fiskar -= 1
    nya_fiskar = np.where(alla_fiskar == -1)[0]
    
    alla_fiskar[nya_fiskar] = 6
    alla_fiskar = np.append(alla_fiskar, [8 for _ in range(nya_fiskar.size)])

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.size} st.")

Antalet fiskar efter 80 dagar är 5934 st.


### Del 2

In [14]:
# Betydligt effektivare lösning :D

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80
#antal_dagar = 256

fiskar_vid_dag_0 = np.array(eval(läsin_fil(sökväg)[0]))
alla_fiskar = np.array([(fiskar_vid_dag_0 == i).sum()  for i in range (9)], np.int64)

for i in range(antal_dagar):

    alla_fiskar = np.roll(alla_fiskar, -1)
    alla_fiskar[6] += alla_fiskar[8]

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.sum()} st.")

Antalet fiskar efter 80 dagar är 5934 st.


## Lucka 7
### Del 1


In [15]:
sökväg = "files/exempel 7.txt"
sökväg = "files/input 7.txt"

krabbor_position = np.array(eval(läsin_fil(sökväg)[0]))
intervall_positioner = range(krabbor_position.min(), krabbor_position.max() + 1)

In [16]:
lägsta_bränsleförbrukning = min([np.absolute(krabbor_position - p).sum() for p in intervall_positioner])
print(f"Den lägta bränsleförbrukningen är {lägsta_bränsleförbrukning}")

Den lägta bränsleförbrukningen är 348664


### Del 2

In [17]:
lägsta_bränsleförbrukning = min([sum([(i**2+i)/2 for i in (np.absolute(krabbor_position - p))]) for p in intervall_positioner]) 

print(f"Den lägta bränsleförbrukningen är {lägsta_bränsleförbrukning}")

Den lägta bränsleförbrukningen är 100220525.0


In [18]:
# Smaratare sätt är att bara räkna ut bränsleförbrukningen för positionerna närmast medelvärdet.
np.floor(krabbor_position.mean()), np.ceil(krabbor_position.mean())

(479.0, 480.0)

## Lucka 8
### Del 1


In [19]:
sökväg = "files/exempel 8.txt"
#sökväg = "files/input 8.txt"

text = läsin_fil(sökväg)
text = [ text[i].strip() + " " + text[i+1]  for i in range(0, len(text), 2)] # Endast för exempeldata med radbrytning
data = [rad.split(" ") for rad in text]

In [20]:
# Alternativ lösning 1
antal_siffror = 0
for rad in data:
    for siffra in rad[11:]:
        antal_segment = len(siffra.strip())
        if 2 <= antal_segment <= 4 or antal_segment == 7:
            antal_siffror += 1
           
print(f"Antalet siffror (1, 4, 7, 8) är: {antal_siffror}")

Antalet siffror (1, 4, 7, 8) är: 26


In [21]:
# Alternativ lösning 2
antal_siffror = sum([sum([(1 if 2 <= len(siffra.strip()) <= 4 or len(siffra.strip()) ==7 else 0) for siffra in rad[11:]]) for rad in data])

print(f"Antalet siffror (1, 4, 7, 8) är: {antal_siffror}")

Antalet siffror (1, 4, 7, 8) är: 26


### Del 2

Vilken röra...

In [22]:
def hitta_låga_ingångar(display_siffra):
    """Hitta de rader i kopplingschemat som motsvarare bokstäver som inte förekommer i strängen."""

    ingångar = [i for i in  range (7)]
    for bokstav in display_siffra:
        ingångar[ord(bokstav) - ord('a')] = -1
    ingångar = list(set(ingångar))
    ingångar.sort()
    ingångar.pop(0)
    return ingångar          

In [23]:
segment_per_siffra = {  (0, 1, 2, 4, 5, 6)      : 0,
                        (2, 5)                  : 1,
                        (0, 2, 3, 4, 6)         : 2,
                        (0, 2, 3, 5, 6)         : 3,
                        (1, 2, 3, 5)            : 4,
                        (0, 1, 3, 5, 6)         : 5,
                        (0, 1, 3, 4, 5, 6)      : 6,
                        (0, 2, 5)               : 7,
                        (0, 1, 2, 3, 4, 5, 6)   : 8,
                        (0, 1, 2, 3, 5, 6)      : 9
}

total_summa = 0

for display_i in data:
    kopplingsschema = np.ones((7, 7))

    # Kopplingar som kan uteslutas direkt beroende på antal segment aktiva
    for display_siffra_j in display_i:
        display_siffra_j = display_siffra_j.strip()
       
        antal_segment = len(display_siffra_j)
        
        if antal_segment == 2:
            segment = (2, 5)
            aktiv_lista = True 
                   
        elif antal_segment == 3:
            segment = (0, 2, 5)
            aktiv_lista = True  

        elif antal_segment == 4:
            segment = (1, 2, 3, 5)
            aktiv_lista = True  

        elif antal_segment == 5:
            segment = (1, 2, 4, 5)
            aktiv_lista = False 

        elif antal_segment == 6:
            segment = (2, 3, 4)
            aktiv_lista = False
        else:
            continue

        if aktiv_lista:
            for ingång in display_siffra_j:
                ingång_index = ord(ingång)-ord('a')
            
                for k in range(7):
                    if not k in segment:
                        kopplingsschema[ingång_index, k] = 0  
                    

        låga_ingångar =hitta_låga_ingångar(display_siffra_j)

        for rad in låga_ingångar:
            for k in range(7):
                if (k in segment and aktiv_lista) or (not k in segment and not aktiv_lista):
                    kopplingsschema[rad, k] = 0
                    

    kopplingsschema_o = 0 
    while not (kopplingsschema == kopplingsschema_o).all():
        kopplingsschema_o = kopplingsschema
        
        for display_siffra_k in display_i:
            display_siffra_k = display_siffra_k.strip()
            antal_segment = len(display_siffra_k)
            
            if antal_segment == 5:

                låga_ingångar =hitta_låga_ingångar(display_siffra_k)
            
                for j, ingång_j in enumerate(låga_ingångar):
                    if kopplingsschema[ingång_j, 2] == 0 and kopplingsschema[ingång_j, 4] == 0:
                        kopplingsschema[låga_ingångar[1-j], 2] = 0  
        
                    if kopplingsschema[ingång_j, 1] == 0 and kopplingsschema[ingång_j, 5] == 0:
                        kopplingsschema[låga_ingångar[1-j], 5] = 0  
                   
        # Sudoku rensa kol omm endast 1 etta på rad  
        for j, ingång_j in enumerate(kopplingsschema):
            if ingång_j.sum() == 1:
                index = np.where(ingång_j == 1)[0][0]
                kopplingsschema[:,index] = 0 
                kopplingsschema[j, index ] = 1 

    # Omvandla indata till siffror
    siffror = ""
    for display_siffra_l in display_i[-4:]:
        display_siffra_l = display_siffra_l.strip()

        aktiva_segment =[ np.where(kopplingsschema[ ord(tecken) - ord('a')])[0][0] for tecken in display_siffra_l]
        aktiva_segment.sort()

        siffror += str(segment_per_siffra[tuple(aktiva_segment)])

    total_summa += int(siffror)

print(f"Den totala summan av talen på displayerna är {total_summa}")    

Den totala summan av talen på displayerna är 61229


## Lucka 9
### Del 1


In [24]:
sökväg = "files/exempel 9.txt"
#sökväg = "files/input 9.txt"

text = läsin_fil(sökväg)

karta = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])
karta_inramad = np.ones(np.array(karta.shape)+2, np.int16) *10
karta_inramad[1:-1, 1:-1] = karta

In [25]:
# Hitta den här på nätet :-) Ändrade dock från <= til <
def local_minima(array2d):
    return ((array2d < np.roll(array2d,  1, 0)) &
            (array2d < np.roll(array2d, -1, 0)) &
            (array2d < np.roll(array2d,  1, 1)) &
            (array2d < np.roll(array2d, -1, 1)))


In [26]:
bool_array = local_minima(karta_inramad)[1:-1, 1:-1]      
svar = (bool_array * (karta + 1)).sum()
print(f"Summan av risknivåerna för kartans minpunkter är {svar}" )

Summan av risknivåerna för kartans minpunkter är 15


### Del 2

In [27]:
minpunkter = np.where(bool_array)
bassängstorlekar = []

for rad, kol in zip(minpunkter[0]+1, minpunkter[1]+1):

    bassäng = np.array(np.zeros(karta_inramad.shape), np.bool8)

    bassäng[rad, kol] = True

    punkter_att_kontrollera = [(rad, kol)] 

    while punkter_att_kontrollera:
        (rad, kol) = punkter_att_kontrollera.pop()
        
        närliggande_punkter = [(rad - 1, kol), (rad + 1, kol), (rad, kol - 1), (rad, kol + 1)]
        for närliggande_punkt in närliggande_punkter:

            if not bassäng[närliggande_punkt] and karta_inramad[närliggande_punkt] < 9:
                bassäng[närliggande_punkt] = True
                punkter_att_kontrollera.append(närliggande_punkt)

    bassängstorlekar.append(bassäng.sum())

bassängstorlekar.sort()
svar = np.array(bassängstorlekar[-3:]).prod()

print(f"Produkten av arean av de tre största bassängerna är {svar}.")

Produkten av arean av de tre största bassängerna är 1134.


## Lucka 10
### Del 1


In [28]:
# Inläsning av indata
sökväg = "files/exempel 10.txt"
#sökväg = "files/input 10.txt"

text = läsin_fil(sökväg) 

# Nödvändiga data gemensammt del 1 och del 2
möjliga_startparenteser = ('(', '[', '{', '<')
möjliga_slutparenteser = {')' : '(', ']' : '[', '}' : '{', '>' : '<'}

text


['[({(<(())[]>[[{[]{<()<>>\n',
 '[(()[<>])]({[<{<<[]>>(\n',
 '{([(<{}[<>[]}>{[]{[(<()>\n',
 '(((({<>}<{<{<>}{[]{[]{}\n',
 '[[<[([]))<([[{}[[()]]]\n',
 '[{[{({}]{}}([{[{{{}}([]\n',
 '{<[[]]>}<{[{[{[]{()[[[]\n',
 '[<(<(<(<{}))><([]([]()\n',
 '<{([([[(<>()){}]>(<<{{\n',
 '<{([{{}}[<[[[<>{}]]]>[]]\n']

In [29]:
# Nödvändig data
poäng_felaktiga_parenteser = {')' : 3, ']' : 57, '}' : 1197, '>' : 25137}

# Loopa igenom varje rad och tecken i indatan
totalpoäng = 0
for rad in text:
    startparenteser = []
    for tecken in rad.strip():
        
        # Kontrollera vilken typ av tecken 
        if tecken in möjliga_startparenteser:                       # tecken är en startparentes
            startparenteser.append(tecken)                          # Spara öppningsparentes i lista
        elif möjliga_slutparenteser[tecken] == startparenteser[-1]: # tecken är matchar senaste startparentes
            startparenteser.pop()                                   # Avlägsna matchad parentes ur lista
        else:                      
            totalpoäng += poäng_felaktiga_parenteser[tecken]        # Addera poäng för upptäckt felaktighet
            break                                                   # Byt till nästa rad 

print(f"Den totala poängen för ogiltiga tecken är {totalpoäng}")        

Den totala poängen för ogiltiga tecken är 26397


### Del 2

In [30]:
# Nödvändig data
poäng_saknade_parenteser = {'(' : 1, '[' : 2, '{' : 3, '<' : 4}

# Loopa igenom varje rad i indata
poäng_per_godkänd_rad = []
for rad in text:
    
    # Loopa igenom alla tecken i aktuell rad
    startparenteser = []
    for tecken in rad:
        
        # Kontrollera vilken typ av tecken 
        if tecken in möjliga_startparenteser:                           # tecken är en startparentes
            startparenteser.append(tecken)                              # Spara öppningsparentes i lista
        elif tecken in möjliga_slutparenteser:                          # Kontrollera om tecken är en slutparentes
            if möjliga_slutparenteser[tecken] == startparenteser[-1]:   # tecken är matchar senaste startparentes
                startparenteser.pop()                                   # Avlägsna matchad parentes ur lista
            else:                                                       # Annars är tecken == '\n' -> ny rad    
                break                                                   # Byt till nästa rad                                                

    # Beräkna poäng om giltig rad
    if tecken == '\n': 
        poäng = 0
        for p in reversed(startparenteser): # Tilldela en slutparentes till alla öppna parenteser i rätt ordning
            poäng *= 5
            poäng += poäng_saknade_parenteser[p]

        poäng_per_godkänd_rad.append(poäng)

# Hitta värdet som ligger i mitten
poäng_per_godkänd_rad.sort()
mitten_index = len(poäng_per_godkänd_rad)// 2

print(f"Den mittersta poängen i autofyll-tävlingen är {poäng_per_godkänd_rad[mitten_index]}")  

Den mittersta poängen i autofyll-tävlingen är 288957


## Lucka 11
### Del 1


In [31]:
# Inläsning av indata
sökväg = "files/exempel 11.txt"
#sökväg = "files/input 11.txt"

text = läsin_fil(sökväg) 

text

['5483143223\n',
 '2745854711\n',
 '5264556173\n',
 '6141336146\n',
 '6357385478\n',
 '4167524645\n',
 '2176841721\n',
 '6882881134\n',
 '4846848554\n',
 '5283751526\n']

In [32]:
def dumbo_flash(rad, kol):
    """Blinkand dumbobläckfisk
    Triggar angränsande bläckfiskar.
    Ange position i nätverket"""   
    
    # Alla omgivande punkter
    närliggande_punkter = [(rad - 1, kol), (rad + 1, kol), (rad, kol - 1), (rad, kol + 1), (rad - 1, kol - 1), (rad + 1, kol -1), (rad - 1, kol + 1), (rad + 1, kol + 1)]

    for (r, k) in närliggande_punkter:
        
        # Kontrollera att punkten inte ligger utanför nätverk
        if not 0 <= r < dumbo_grid.shape[0] or not 0 <= k < dumbo_grid.shape[1]: 
            continue

        # Öka energinivå i punkten 
        dumbo_grid[r, k] += 1 

        # Kontrollera om punkten blinkar
        if dumbo_grid[r, k] == kritisk_energinivå + 1:   # Om högre -> har redan blinkat
            dumbo_flash(r, k)


In [33]:
# Konstanter
antal_tidssteg = 100
kritisk_energinivå =9

# Skapa grid med bläckfiskar
dumbo_grid = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])

print("Utgångsläge\n", dumbo_grid)

totalt_antal_ljusblinkningar = 0


# Loopa genom alla tidssteg
for tids_steg in range(antal_tidssteg):
    
    # Öka engerginivån hos alla bläckfiskar   
    dumbo_grid += 1

    # Blinka lilla bläckfisk där...
    rader, kollonner = np.where(dumbo_grid > kritisk_energinivå)
    for rad, kol in zip(rader, kollonner):
        dumbo_flash(rad, kol)

    # Nollställ energinivån hos alla bläckfiskar som blinkat
    dumbo_grid[dumbo_grid > kritisk_energinivå] = 0

    # Räkna poäng
    totalt_antal_ljusblinkningar += dumbo_grid.size - np.count_nonzero(dumbo_grid)

print(f"Det totala antalet ljusblinkningar efter {antal_tidssteg} steg är {totalt_antal_ljusblinkningar}.")

Utgångsläge
 [[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]
Det totala antalet ljusblinkningar efter 100 steg är 1656.


### Del 2

In [34]:
# Konstanter
kritisk_energinivå =9

# Skapa grid med bläckfiskar
dumbo_grid = np.array([[ int(siffra) for siffra in rad.strip()] for rad in text])

print("Utgångsläge\n", dumbo_grid)

# Loopa genom tills alla bläckfiskar blinkar synkront
antal_steg = 0
while dumbo_grid.sum() != 0:
    antal_steg += 1

    # Öka engerginivån hos alla bläckfiskar   
    dumbo_grid += 1

    # Blinka lilla bläckfisk där...
    rader, kollonner = np.where(dumbo_grid > kritisk_energinivå)
    for rad, kol in zip(rader, kollonner):
        dumbo_flash(rad, kol)

    # Nollställ energinivån hos alla bläckfiskar som blinkat
    dumbo_grid[dumbo_grid > kritisk_energinivå] = 0
   
print("\nEfter sista steget\n", dumbo_grid)
print(f"\nDet totala antalet steg tills alla bläckfiskar blinkar synkront är {antal_steg}.")

Utgångsläge
 [[5 4 8 3 1 4 3 2 2 3]
 [2 7 4 5 8 5 4 7 1 1]
 [5 2 6 4 5 5 6 1 7 3]
 [6 1 4 1 3 3 6 1 4 6]
 [6 3 5 7 3 8 5 4 7 8]
 [4 1 6 7 5 2 4 6 4 5]
 [2 1 7 6 8 4 1 7 2 1]
 [6 8 8 2 8 8 1 1 3 4]
 [4 8 4 6 8 4 8 5 5 4]
 [5 2 8 3 7 5 1 5 2 6]]

Efter sista steget
 [[0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0]]

Det totala antalet steg tills alla bläckfiskar blinkar synkront är 195.


## Lucka 12
### Del 1


In [35]:
import networkx as nx

# Inläsning av indata
sökväg = "files/exempel 12 0.txt"
#sökväg = "files/exempel 12 1.txt"
#sökväg = "files/exempel 12 2.txt"
#sökväg = "files/input 12.txt"

text = läsin_fil(sökväg) 

# Skapa grafobjekt
graf_grottsystem = nx.Graph()

# Skapa kanter
[graf_grottsystem.add_edge(*tuple(kant.strip().split('-'))) for kant in text]

graf_grottsystem.nodes

NodeView(('start', 'A', 'b', 'c', 'd', 'end'))

In [36]:
def kontrollera_nästa_nod(nod, väg):

    # Kontrollera om liten grotta och om den redan är besökt. Avsluta i så fall.
    if nod.islower() and (nod in väg):
        return

    # Lägg till aktuell grott till vägen.
    väg = väg + [nod]

    # Om aktuell grotta är utgången spara vägen som godkänd väg och avsluta
    if nod == "end":
        godkända_vägar.append(väg)
        return

    # Hitta alla angränsande grottor och kontrollera dessa.
    närliggande_grottor = nx.neighbors(graf_grottsystem, nod)
    for grotta in närliggande_grottor:
        kontrollera_nästa_nod(grotta, väg)



In [37]:
# Sätt startvärden
startposition = "start"
godkända_vägar = []
väg_ = []

# Kontrollera första grottan
kontrollera_nästa_nod(startposition, väg_)

# Räkna alla godkända vägar från start till utgången
antal_godkända_vägar = len(godkända_vägar)
print(f"Antalet godkända vägar ut ur grottsystemet är {antal_godkända_vägar}.")

Antalet godkända vägar ut ur grottsystemet är 10.


### Del 2

In [38]:
def väg_dubletter(väg):
    """Kontrollerar om det finns dubletter av små grottor i angiven väg."""
    besökta_små_grottor = []
    [besökta_små_grottor.append(nod) if nod.islower() else None for nod in väg]
    
    return sorted(list(set(besökta_små_grottor))) != sorted(besökta_små_grottor)


def kontrollera_nästa_nod_2(nod, väg):
    """Konrollerar om nästa nod är godkänd och triggar följande noder om så är fallet. Annars avslutas funktionen."""
    
    # Kontrollera om liten grotta och om den redan är besökt.
    if nod.islower() and (nod in väg):
        
        # Kontrollera om det finns någon liten grotta som besökts två ggr eller aktuell grotta är startpunkten. I så fall återgå.
        if väg_dubletter(väg) or nod == "start": 
            return
    
    # Lägg till aktuell grott till vägen.
    väg = väg + [nod]

    # Om aktuell grotta är utgången spara vägen som godkänd väg och avsluta
    if nod == "end":
        godkända_vägar.append(väg)
        return

    # Hitta alla angränsande grottor och kontrollera dessa.
    närliggande_grottor = nx.neighbors(graf_grottsystem, nod)
    for grotta in närliggande_grottor:
        kontrollera_nästa_nod_2(grotta, väg)


In [39]:
# Sätt startvärden
startposition = "start"
godkända_vägar = []
väg_ = []


# Kontrollera första grottan
kontrollera_nästa_nod_2(startposition, väg_)


# Räkna alla godkända vägar från start till utgången
antal_godkända_vägar = len(godkända_vägar)
print(f"Antalet godkända vägar ut ur grottsystemet är {antal_godkända_vägar}.")

Antalet godkända vägar ut ur grottsystemet är 36.


## Lucka 13
### Del 1


In [40]:
def vik_ark(vikning):
    """Viker papersarket en gång på den position den axel som anges i vikning."""
    
    global punkter_på_arket
    axel, pos = vikning
    m, n = punkter_på_arket.shape
    
    # Kontrollera dimension och slå samman rader/kolonner utifrån och in. 
    if axel == 'x':
        for i in range(pos):
            punkter_på_arket[:, i] = punkter_på_arket[:, i] | punkter_på_arket[:, n-i-1] 

        # Spara bara den aktuella halvan av arket.
        punkter_på_arket = punkter_på_arket[:, 0 : pos]

    elif axel == 'y':
        for i in range(pos):
            punkter_på_arket[i, :] = punkter_på_arket[i, :] | punkter_på_arket[m-i-1, :] 
        
        # Spara bara den aktuella halvan av arket.
        punkter_på_arket = punkter_på_arket[0 : pos, :]
    

In [41]:
# Inläsning av indata
sökväg = "files/exempel 13.txt"
sökväg = "files/input 13.txt"

text = läsin_fil(sökväg) 

punkternas_koordinater =[]
vikningar = []
for rad in text:
    if rad[0] == 'f':
        vikningar.append((rad[11], int(rad[13:])))

    elif rad[0] != '\n':
        punkternas_koordinater.append(list(eval(rad)))
  
# Hitta största värden på rad och kol
max_kol, max_rad = max([p[0] for p in punkternas_koordinater]), max([p[1] for p in punkternas_koordinater])

# Skapa arketsarket
punkter_på_arket = np.array(np.zeros((max_rad + 1, max_kol + 1)), bool)

# Sätt ut punktern
for kol, rad in punkternas_koordinater: 
    punkter_på_arket[rad, kol] = True

punkter_på_arket_bak = punkter_på_arket.copy()

In [42]:
punkter_på_arket = punkter_på_arket_bak.copy()

# Vi arket en gång
vik_ark(vikningar[0])

print(f"Antalet punkter efter en vikninga av pappersarket är {punkter_på_arket.sum()} styken.")

Antalet punkter efter en vikninga av pappersarket är 678 styken.


### Del 2

In [43]:
punkter_på_arket = punkter_på_arket_bak.copy()

# Vik arket enligt instruktionerna
for vikning in vikningar:
    vik_ark(vikning)
    
# Skriv ut svaret
print("Koden för att starta värmekameran är:\n")
for rad_i in punkter_på_arket:
    for pos in rad_i:
        print(('███'if pos else '   '), end="")
    print("")

Koden för att starta värmekameran är:

████████████      ██████      ████████████   ███      ███   ███            ███      ███   ████████████   ████████████   
███            ███      ███   ███            ███      ███   ███            ███      ███            ███   ███            
█████████      ███            █████████      ████████████   ███            ████████████         ███      █████████      
███            ███            ███            ███      ███   ███            ███      ███      ███         ███            
███            ███      ███   ███            ███      ███   ███            ███      ███   ███            ███            
████████████      ██████      ███            ███      ███   ████████████   ███      ███   ████████████   ███            


## Lucka 14
### Del 1


In [44]:
# Inläsning av indata
sökväg = "files/exempel 14.txt"
#sökväg = "files/input 14.txt"

text = läsin_fil(sökväg)

# Startvärde för polymer
polymer_start= text[0].strip()


In [45]:
antal_iterationer = 10
polymer = polymer_start 

# Par för insättning av nya monomerer
monomerpar_insätt_ämne = {p[0:2] : p[6] for p in text[2:]}

for i in range(antal_iterationer):
    #print("Iteration:", i, "Längden polymer:", len(polymer))
   
    # Sätt in ny monomer mellan varje tidigare par
    polymer_tmp = polymer[0]
    for m1,m2 in zip(polymer[:-1], polymer[1:]):
        polymer_tmp +=monomerpar_insätt_ämne[m1+m2] + m2
    polymer = polymer_tmp    

# Beräkna förekomst och svar
ämne_förekomst = {m : polymer.count(m)  for m in set(monomerpar_insätt_ämne.values())}
svar = max(ämne_förekomst.values()) - min(ämne_förekomst.values())

print(f"Skillnaden mellan antalet av det vanligast förekommande och minst vanliga ämnet är {svar}.")

Skillnaden mellan antalet av det vanligast förekommande och minst vanliga ämnet är 1588.


### Del 2

In [46]:
antal_iterationer = 40
polymer = polymer_start 

# Par för insättning av nya monomerer
monomerpar_nya_par = {p[0:2] : [p[0] + p[6], p[6] + p[1]] for p in text[2:]}

# Räkna antalet par
monomerpar_antal = {p : 0 for p in monomerpar_nya_par.keys()}
for m1,m2 in zip(polymer[:-1], polymer[1:]):
    monomerpar_antal[m1+m2] += 1

for i in range(antal_iterationer):

    # Lägg till nyaskapade par och ta bort de gamla delade
    monomerpar_antal_tmp = monomerpar_antal.copy()
    for par in monomerpar_antal:
        monomerpar_antal_tmp[monomerpar_nya_par[par][0]] += monomerpar_antal[par] 
        monomerpar_antal_tmp[monomerpar_nya_par[par][1]] += monomerpar_antal[par] 
        monomerpar_antal_tmp[par] -= monomerpar_antal[par] 
    monomerpar_antal = monomerpar_antal_tmp.copy()
   
# Räkna förekomsten av respektive ämne
for m in  set(monomerpar_insätt_ämne.values()):
    ämne_förekomst[m] = 0
    for k in monomerpar_antal.keys():
        if k[0] == m:   # Räkna första ämnet i varje par
            ämne_förekomst[m] += monomerpar_antal[k]
ämne_förekomst[polymer_start[-1]] += 1 # Lägg till sista ämnet som ej är start på något par

# Beräkna svaret
svar = max(ämne_förekomst.values())-min(ämne_förekomst.values())
print(f"Skillnaden mellan antalet av det vanligast förekommande och minst vanliga ämnet är {svar}.")

Skillnaden mellan antalet av det vanligast förekommande och minst vanliga ämnet är 2188189693529.


## Lucka 15
### Del 1


In [47]:
# Inläsning av indata
sökväg = "files/exempel 15.txt"
#sökväg = "files/input 15.txt"

text = läsin_fil(sökväg)
text = [rad.strip() for rad in text]

text_bak = text.copy()

In [52]:
# Kör för att lösa del 2
del_2()

# Skapa grafobjekt
graf_grotta = nx.Graph()

# Skapa kanter
m = len(text)
n = len(text[0]) 
for i, rad in enumerate(text):
    for j, kol in enumerate(rad):
        nod = i * n + j
        if j < n -1:
            graf_grotta.add_edge(*((nod, nod+1))) 
        
        if i < m - 1:
            graf_grotta.add_edge(*((nod, nod+n)))

        graf_grotta.add_node(nod, risk=int(kol))

# Lambdafunktion för att beräkna viktning för kant
risk_kant =lambda a, b, c : graf_grotta.nodes[b]['risk']

# Hitta säkraste vägen genom grottan
säkraste_vägen = nx.shortest_path(graf_grotta, source=0, target=graf_grotta.number_of_nodes() - 1, weight=risk_kant, method='dijkstra')

# Beräkna svar
svar = sum([graf_grotta.nodes[nod]['risk'] for nod in säkraste_vägen[1:]])
print(f"Den sammanlagda risknivån för den säkraste vägen genom grottan {svar}.")

Den sammanlagda risknivån för den säkraste vägen genom grottan 40.


### Del 2

In [51]:
def del_2():
        
    text = text_bak.copy()
    text2 = text.copy()
    antal_ggr_större = 5

    # Nytt värde för alla tecken
    byten = (('9', 'x'), ('8', '9'), ('7', '8'), ('6', '7'), ('5', '6'), ('4', '5'), ('3', '4'), ('2', '3'), ('1', '2'), ('x', '1'), )

    for i in range(antal_ggr_större + 2 * antal_ggr_större - 1):

        # Öka värdena med ett i rutan    
        for j, rad in enumerate(text2):
            for från, till in byten:
                rad = rad.replace(från, till) 
            text2[j] = rad
        
        
      
        antal_rader_text2 = len(text2)

        # Utöka grottan en ruta i sidled
        for del_av_grotta in range(0, len(text), antal_rader_text2):
            if len(text[del_av_grotta]) < antal_ggr_större * len(text2[0]):
                konkatinerade_rader = [rad1 +  rad2 for rad1, rad2 in zip(text[del_av_grotta: del_av_grotta + antal_rader_text2], text2)]
                text[del_av_grotta: del_av_grotta + antal_rader_text2] = konkatinerade_rader
       
        # Kontollera att inte utanför grottan annars lägg till en ruta neråt
        if i + 1 < antal_ggr_större:
            text += text2
        
   

## Lucka 16
### Del 1 & 2


In [53]:
def läsin_paket():
    global index
    alla_tal_paket = []

    # Läs av version och index
    version = int(binär_sträng[index : index + 3], 2)
    index += 3 
    alla_versioner.append(version)
    typ = int(binär_sträng[index : index + 3], 2) 
    index += 3 

    # Kontrollera om paketet innehåller ett tal eller en operation
    if typ == 4: # Tal
        
        # Läs in 5 bitar i taget tills talet är klart
        tal = ""
        while True: # Varför finns det inte do until-loopar i Python? 🙄
            tal += binär_sträng[index + 1 : index + 5]
            if binär_sträng[index] == '0':
                index += 5 
                break
            index += 5 

        # Beräkna och returnera talet i paketet
        return int(tal, 2)

    else: # Operation
        # Kontrollera vilken typ av längdinformation som används 
        if binär_sträng[index] == '0': # 15 bitar
            index += 1 

            #Beräkna antal bitar subpaketen upptar
            antal_tecken_subpaket = int(binär_sträng[index : index + 15], 2)      
            index += 15 
      
            # Läs in alla subpaket
            index_slut_subpaket = index + antal_tecken_subpaket
            while index < index_slut_subpaket:
                alla_tal_paket.append(läsin_paket()) 
 
        elif binär_sträng[index] == '1': # 11 bitar
            index += 1 
           
            #Beräkna antal subpaketen som ingår i paketet
            antal_subpaket = int(binär_sträng[index : index + 11], 2)
            index += 11
            
            # Läs in alla subpaket
            for i in range(antal_subpaket):
                alla_tal_paket.append(läsin_paket())

        # Kontrollera vilken operation som ska utföras och returnera resultat
        if typ == 0: # Summa
            return sum(alla_tal_paket)
        elif typ == 1: # produkt
            return math.prod(alla_tal_paket)
        elif typ == 2: # Minimum
            return min(alla_tal_paket)
        elif typ == 3: # Maximum
            return max(alla_tal_paket)
        elif typ == 5: # Större än
            return int(alla_tal_paket[0] > alla_tal_paket[1])
        elif typ == 6: # Mindre än
            return int(alla_tal_paket[0] < alla_tal_paket[1])       
        elif typ == 7: # Lika med
            return int(alla_tal_paket[0] == alla_tal_paket[1])  
    

In [54]:
import math

# Inläsning av indata
#sökväg = "files/exempel/exempel 16 1.txt"
#sökväg = "files/exempel/exempel 16 2.txt"
#sökväg = "files/exempel/exempel 16 3.txt"
#sökväg = "files/exempel/exempel 16 4.txt"
#sökväg = "files/exempel/exempel 16 5.txt"
#sökväg = "files/exempel/exempel 16 6.txt"
#sökväg = "files/exempel/exempel 16 7.txt"
#sökväg = "files/exempel/exempel 16 8.txt"
#sökväg = "files/exempel/exempel 16 9.txt"
#sökväg = "files/exempel/exempel 16 10.txt"
#sökväg = "files/exempel/exempel 16 11.txt"
#sökväg = "files/exempel/exempel 16 12.txt"
#sökväg = "files/exempel/exempel 16 13.txt"
#sökväg = "files/exempel/exempel 16 14.txt"
#sökväg = "files/exempel/exempel 16 15.txt"
sökväg = "files/input 16.txt"

text = läsin_fil(sökväg)

# Konvertera från hex till binär
hexnummer = dict((  ("0", "0000"),
                    ("1", "0001"),
                    ("2", "0010"),
                    ("3", "0011"),
                    ("4", "0100"),
                    ("5", "0101"),
                    ("6", "0110"),
                    ("7", "0111"),
                    ("8", "1000"),
                    ("9", "1001"),
                    ("A", "1010"),
                    ("B", "1011"),
                    ("C", "1100"),
                    ("D", "1101"),
                    ("E", "1110"),
                    ("F", "1111"),
))
binär_sträng = "".join([hexnummer[t] for t in text[0].strip()])

# Begynnelsevärden
index = 0
alla_versioner = []

# Läs in paket
svar = läsin_paket()

# Svar
print(f"Del 1. Summan av versionsnumren {sum(alla_versioner)}")
print(f"Del 2. Beräkningen av paketet ger {svar}")


Del 1. Summan av versionsnumren 1007
Del 2. Beräkningen av paketet ger 834151779165


## Lucka 17
### Del 1 & 2


In [124]:
# Inläsning av indata
sökväg = "files/exempel 17.txt"
sökväg = "files/input 17.txt"

text = läsin_fil(sökväg)

# Läs in målet
data = text[0].split()
target =  data[2][2:-1].split("..") +  data[3][2:].split("..")
target = [ int(t) for t in target]

# Minsta och största hastigheter som har möjlighet att nå målet
min_x_hastighet = math.ceil(-0.5 + math.sqrt(2 * target[0] + 0.25)) # Lös ut n ur: summa = n(n+1)/2
max_x_hastighet = target[1] + 1
min_y_hastighet = target[2] - 1
max_y_hastighet = -target[2] + 1

max_y = []

# Prova alla möjliga kombinationer av utgångshastigheter
for x_ut_hastighet in range(min_x_hastighet, max_x_hastighet + 1):
    for y_ut_hastighet in range(min_y_hastighet,max_y_hastighet):
        
        # Utgångsvärde variabler
        x_hastighet, y_hastighet = x_ut_hastighet, y_ut_hastighet
        x_position, y_position = 0, 0
        x_väg, y_väg = [], []

        # Fortsätta framåt så länge som inte målet är passerat
        while x_position <= target[1] and y_position >= target[2]: 
            # Spara vägen sonden färdas
            x_väg.append( x_position)
            y_väg.append( y_position)

            # Ändra position
            x_position += x_hastighet
            y_position += y_hastighet

            # Ändra hastigheten
            x_hastighet -= 1 if x_hastighet > 0 else -1 if x_hastighet > 0 else 0
            y_hastighet -= 1

        # Kontollera att sonden hamnar i målområdet och spara högst höjden
        if target[0] <= x_väg[-1] <= target[1] and target[2] <= y_väg[-1] <= target[3] :
            max_y.append(max(y_väg))

# Beräkna svar
print(f"Del 1. Maximal höjd som kan uppnås är {max(max_y)}.")
print(f"Del 2. Antal utgångshastigheter som når målet är {len(max_y)}.")


Del 1. Maximal höjd som kan uppnås är 33670.
Del 2. Antal utgångshastigheter som når målet är 4903.


## Lucka 18
### Del 1


In [657]:
import re

# Inläsning av indata
#sökväg = "files/exempel 18 1.txt"
sökväg = "files/exempel 18 2.txt"
#sökväg = "files/input 18.txt"

text = läsin_fil(sökväg)
text

['[[[0,[5,8]],[[1,7],[9,6]]],[[4,[1,2]],[[1,4],2]]]\n',
 '[[[5,[2,8]],4],[5,[[9,9],0]]]\n',
 '[6,[[[6,2],[5,6]],[[7,6],[4,7]]]]\n',
 '[[[6,[0,7]],[0,9]],[4,[9,[9,0]]]]\n',
 '[[[7,[6,4]],[3,[1,3]]],[[[5,5],1],9]]\n',
 '[[6,[[7,3],[3,2]]],[[[3,8],[5,7]],4]]\n',
 '[[[[5,4],[7,7]],8],[[8,3],8]]\n',
 '[[9,3],[[9,9],[6,[4,9]]]]\n',
 '[[2,[[7,7],7]],[[5,8],[[9,3],[0,2]]]]\n',
 '[[[[5,2],5],[8,[3,7]]],[[5,[7,5]],[4,4]]]\n']

In [683]:
def explodera(tal_att_förenkla: str) -> str:  
    """Tar in ett fisktal. Letar upp första innersta talparet som är nästlat på minst nivå 5. Om det existerar exploderas talparet och fisktalet fisktalet returneras."""

    # Sök igenom strängen med fisktalet
    antal_v_parenteser = 0
    for i, tecken in enumerate(tal_att_förenkla):
        
        # Ändra nivå av nästling
        if tecken == "[":
            antal_v_parenteser += 1
            
            # Hitta nästkommande innersta talpar
            talpar = re.findall("\[\d\d*,\d\d*\]" , tal_att_förenkla[i:])[0]
            
            # Hitta första innersta talparet med minst 5 '['
            if antal_v_parenteser >= 5 and tal_att_förenkla[i : i + len(talpar)] == talpar:

                # Hitta siffra före och beräkna nya värdet
                try:
                    tal_före = re.findall("\d\d*", tal_att_förenkla[:i])[-1]
                    nytt_tal_vänster = int(tal_före) + int(eval(talpar)[0])
                except IndexError:
                    tal_före = ''
                    nytt_tal_vänster = ''

                # Hitta siffra efter och beräkna nya värdet
                try: 
                    tal_efter = re.findall("\d\d*", tal_att_förenkla[i:])[2]
                    nytt_tal_höger =int(tal_efter) + int(eval(talpar)[1])
                except IndexError:
                    tal_efter = ''
                    nytt_tal_höger = ''

                # Hitta index för tal före
                for  j in range(len(tal_att_förenkla[:i]), 0, -1):
                    if tal_att_förenkla[j].isdigit(): break
                
                # Explodera talpar
                förenklat_tal = (((tal_att_förenkla[:j-len(tal_före)+1 ] + str(nytt_tal_vänster) + tal_att_förenkla[j+1: i ])  if nytt_tal_vänster != '' else tal_att_förenkla[:i]) # Del före talparet
                                + (tal_att_förenkla[i:].replace(talpar, '0', 1).replace(tal_efter, str(nytt_tal_höger), 1))) # Talparet och del efter

                return förenklat_tal, True # exploderat = True

        elif tecken == "]":
            antal_v_parenteser -= 1
        
    return tal_att_förenkla, False # exploderat = False

In [684]:
def split(tal_att_förenkla: str) -> str:   
    """Tar in ett fisktal och letar upp del av ett talpar som är mer än en siffra. Splittar denna och returnerar fisktalet igen."""
    
    # Hitta alla tal i strängen som är minst två siffror
    flersiffriga_tal = re.findall("\d\d\d*" , tal_att_förenkla)
    
    # Splitta första hittade talet
    if flersiffriga_tal:
        tal = flersiffriga_tal[0]
        index = tal_att_förenkla.index(tal)
        
        # Nytt talpar att sätta in
        ny_split_sträng = f"[{str(math.floor(int(tal)/2))},{str(math.ceil(int(tal)/2))}]" 

        # Byt flersiffrigt tal mot nytt talpar    
        tal_att_förenkla = tal_att_förenkla[: index] + ny_split_sträng + tal_att_förenkla[index + len(tal):]

    return tal_att_förenkla
          

In [685]:
def magnitud(tal: str) -> int:
    """Tar in ett fisktal och returnerar dess magnitud"""
    
    # Iterera tills ingen skillnad mot föregående iteration
    tal_föregående = ""
    while tal != tal_föregående:
        tal_föregående = tal     

        # Hitta alla innersta talpar
        talpar = re.findall("\[\d\d*,\d\d*\]" , tal)

        # Ersätt talpar med dess magnitud
        for tp in talpar:
            ersätt_med = str(3 * eval(tp)[0] + 2 * eval(tp)[1])
            tal = tal.replace(tp, ersätt_med)

    return int(tal)

In [686]:
def förenkla(tal_att_förenkla: str) -> str:
    """Tar in ett fisktal och returnerar det förenklade talet."""
    förenklat_föregående = ''
    while tal_att_förenkla != förenklat_föregående:
        förenklat_föregående = tal_att_förenkla

        # Explodera par
        tal_att_förenkla, ex = explodera(tal_att_förenkla)

        # Split
        if not ex:
            tal_att_förenkla = split(tal_att_förenkla)

    return tal_att_förenkla        

In [687]:
def addition(tal1: str, tal2: str) -> str:
    """Tar in två fisktal och returnerar summan av dessa i förenklad form."""
    return förenkla("[" + ",".join([tal1.strip(), tal2.strip()]) + "]")
   

In [690]:
# Lägg till första talet
summa = text[0].strip()

# Lägg till och förenkla resten av alla tal
for tal in text[1:]:
    summa = addition(summa, tal)

# Beräkna svar
print(summa)
print(f"Magnituden av summan blir {magnitud(summa)}.")


[[[[6,7],[7,7]],[[7,6],[7,6]]],[[[6,6],[7,6]],[[6,0],[9,4]]]]
Magnituden av summan blir 3916.


### Del 2

In [691]:
magnituder = []

# Testa för alla kobinationer av tal
for tal1 in text:
    for tal2 in text:
        
        # Kontrollera att det är två olika tal som adderas
        if tal1 == tal2:
            continue
        
        # Summera och beräkna magnitud för varje kobination
        summa = addition(tal1, tal2)
        magnituder.append(magnitud(summa))

# Beräkna svaret
print(f"Den största möjliga magnituden är {max(magnituder)}.")

Den största möjliga magnituden är 4087.


## Lucka 19
### Del 1


### Del 2

## Lucka 20
### Del 1


### Del 2

## Lucka 21
### Del 1


### Del 2

## Lucka 22
### Del 1


### Del 2

## Lucka 23
### Del 1


### Del 2

## Lucka 24
### Del 1


### Del 2

## Lucka 25
### Del 1


### Del 2