# Kodkalender 2021

## Lucka 1
### Del 1

In [2]:
def läsin_fil(fil):
    
    with open(fil, "r") as f:
        text = f.readlines()

    return text
    
sökväg = "files/exempel 1.txt"
#sökväg = "files/input 1.txt"

lista_mätvärden = [int(l.strip()) for l in läsin_fil(sökväg)]

antal_ökande = sum([mv - lista_mätvärden[i] > 0 for i, mv in enumerate(lista_mätvärden[1:])])

print(f"Antal mätvärden med högre värde än föregående: {antal_ökande}")

Antal mätvärden med högre värde än föregående: 7


### Del 2

In [3]:
antal_ökande_tripletter = sum([mv - lista_mätvärden[i] > 0 for i,mv in enumerate(lista_mätvärden[3:])])

print(f"Antal tripletter med högre värde än föregående: {antal_ökande_tripletter}")


Antal tripletter med högre värde än föregående: 5


## Lucka 2
### Del 1


In [4]:
sökväg = "files/exempel 2.txt"
#sökväg = "files/input 2.txt"

text = läsin_fil(sökväg)
kommandon =[l.split() for l in text]

framåt = sum([(int(k[1]) if k[0] == "forward" else 0)  for k in kommandon])
djup = sum([(-int(k[1]) if k[0] == "up" else int(k[1]) if k[0] == "down" else 0)  for k in kommandon])

print(f"Produkten av position framåt och djup: {framåt * djup}")

Produkten av position framåt och djup: 150


### Del 2

In [5]:
framåt_sum, djup, sikte = 0, 0, 0

for kom in kommandon:
    framåt=0
    kommando, kommando_värde =kom[0], int(kom[1])
    
    if kommando == "forward":
        framåt=kommando_värde
        framåt_sum += framåt 

    elif kommando == "down":
        sikte += kommando_värde
        
    elif kommando == "up":
        sikte -= kommando_värde
    
    djup += sikte * framåt

print(f"Produkten av position framåt och djup: {framåt_sum * djup}")

Produkten av position framåt och djup: 900


## Lucka 3
### Del 1


In [6]:
sökväg = "files/exempel 3.txt"
#sökväg = "files/input 3.txt"

text = läsin_fil(sökväg)
diagnosrapport =[l.split() for l in text]

antal_siffror = len(diagnosrapport[0][0])
antal_rader = len(diagnosrapport)
γ,ε = 0, 0

for i in range (antal_siffror):       
    vanligaste_siffra = round(sum([int(diagnosrapport[j][0][i]) for j in range(antal_rader)])/antal_rader) # Vad ska hända om det är lika? Här kommer 1 prioriteras.

    γ += vanligaste_siffra * 10**(antal_siffror-1-i)
    ε += (1 - vanligaste_siffra) * 10**(antal_siffror-1-i)

energiförbrukning = int(str(ε),base=2)*int(str(γ),base=2)

print(f"Energiförbrukningen är {energiförbrukning}")


Energiförbrukningen är 198


### Del 2

In [7]:
def utvärdering(rapport, prioriterad_siffra ):
    """Utvärderar diagnosrapporten med avseende på vilken siffra som ska prioriteras 
    och väljer ut det enskilda värde uppfyller kriterierna"""
    
    kvarvarande_rader = rapport
    antal_siffror = len(rapport[0][0])

    for i in range (antal_siffror):       
        antal_rader = len(kvarvarande_rader)
        if antal_rader == 1: break

        antal_ettor = sum([int(kvarvarande_rader[j][0][i]) for j in range(antal_rader)])
        antal_nollor = antal_rader - antal_ettor
        
        if  antal_ettor > antal_nollor:
            siffra_att_behålla = prioriterad_siffra
        elif antal_nollor > antal_ettor:
            siffra_att_behålla = 1 - prioriterad_siffra
        else:
            siffra_att_behålla = prioriterad_siffra

        rader_att_spara = []
        for rad in kvarvarande_rader:
            if int(rad[0][i])== siffra_att_behålla:
                rader_att_spara.append(rad)

        kvarvarande_rader = rader_att_spara        
    
    return int(kvarvarande_rader[0][0], 2)

syre_generering = utvärdering(diagnosrapport, 1)
co2_rening = utvärdering(diagnosrapport, 0)
liv = syre_generering * co2_rening

print(f"Livsupppehållande systemen har nivå: {liv}")

Livsupppehållande systemen har nivå: 230


## Lucka 4
### Del 1


In [8]:
import numpy as np

sökväg = "files/exempel 4.txt"
#sökväg = "files/input 4.txt"

def skapa_brickor(text):

    längd_sida_bricka = 5
    brickor = np.zeros(((len(text) - 1) // (längd_sida_bricka + 1), längd_sida_bricka, längd_sida_bricka) , np.int16)
    brick_index = 0

    for rad, text_rad in enumerate(text[2:]): 
        if text_rad:
            for kol, text_kol in enumerate(text_rad.split()):
                brickor[brick_index, rad % 6, kol]  = int(text_kol)

        brick_index = (rad + 1) // 6
    return brickor

def kryssa_bricka():

    tal_index = np.where(bingobrickor==nr)
  
    for i, v in enumerate(tal_index[0]):
        if v in vinnande_brickor:
            continue
        
        bingobrickor[tal_index[0][i], tal_index[1][i], tal_index[2][i]] = -1
        
        if bingobrickor[tal_index[0][i], tal_index[1][i], :].sum() == -5 or bingobrickor[tal_index[0][i], :, tal_index[2][i]].sum() == -5:
            vinnande_brickor.append(tal_index[0][i]) 
            vinnande_nummer.append(nr)


def poängräkning():

    summa_kvarvarande_tal = np.where(bingobrickor[vinnande_brickor[-1]] >= 0, bingobrickor[vinnande_brickor[-1]], 0).sum()
    slutgiltig_poäng = summa_kvarvarande_tal * vinnande_nummer[-1]
    
    print(F"Summan av kvarvarande nummer på bingobrickan: {summa_kvarvarande_tal}. Sita dragna numret: {vinnande_nummer[-1]}")
    print(f"Den slutliga poängen är: {slutgiltig_poäng}")           


text = läsin_fil(sökväg)
dragningslista = eval(text[0]) 
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:

    kryssa_bricka()
    
    if vinnande_brickor:
        print("Bingo!\n")
        break
 
if len(vinnande_brickor) > 1:
    print("Flera brickor har Bingo!\n")
    print(vinnande_brickor)

poängräkning()

Bingo!

Summan av kvarvarande nummer på bingobrickan: 188. Sita dragna numret: 24
Den slutliga poängen är: 4512


### Del 2

In [9]:
bingobrickor = skapa_brickor(text)
vinnande_brickor = []
vinnande_nummer = []

for nr in dragningslista:
    
    kryssa_bricka()
    
    if len(vinnande_brickor) == len(bingobrickor):
        break

poängräkning()

Summan av kvarvarande nummer på bingobrickan: 148. Sita dragna numret: 13
Den slutliga poängen är: 1924


## Lucka 5
### Del 1


In [10]:
def farliga_positioner(karta):
    antal_farliga_positioner = len(np.where(karta>= 2)[0])
    print(f"Antalet farliga positioner är: {antal_farliga_positioner}")


In [11]:
sökväg = "files/exempel 5.txt"
#sökväg = "files/input 5.txt"

text = läsin_fil(sökväg)

linjer_koordinater = np.array([eval(rad.replace(" -> ",',')) for rad in text])
y_dim, x_dim = linjer_koordinater[:, (0, 2)].max() + 1, linjer_koordinater[:, (1, 3)].max() + 1

karta = np.zeros((y_dim, x_dim), np.int8)

In [12]:
for linje in linjer_koordinater:
    if linje[0] == linje [2] or linje[1] == linje [3]:
        
        y =sorted((linje[0],linje[2]))
        x =sorted((linje[1],linje[3]))

        karta[y[0]: y[1]+1, x[0]: x[1]+1] += 1

farliga_positioner(karta)

Antalet farliga positioner är: 5


### Del 2

In [13]:
for linje in linjer_koordinater:

    y =((linje[0],linje[2]))
    x =((linje[1],linje[3]))

    if y[1] - y[0] >= 0 :
        y2 =[yi for yi in range(y[0], y[1] + 1, 1)]
    else:
        y2 =[yi for yi in range(y[0], y[1] - 1, -1)]

    if x[1] - x[0] >= 0:
        x2 =[xi for xi in range(x[0], x[1] +1, 1)]
    else:
        x2 =[xi for xi in range(x[0] ,x[1] - 1, -1)]

    if len(y2) == len(x2):
        for yi, xi in zip(y2, x2):
            karta[yi, xi] += 1 

print(karta.transpose()) 

farliga_positioner(karta)

[[1 0 1 0 0 0 0 1 1 0]
 [0 1 1 1 0 0 0 2 0 0]
 [0 0 2 0 1 0 1 1 1 0]
 [0 0 0 1 0 2 0 2 0 0]
 [0 1 1 2 3 1 3 2 1 1]
 [0 0 0 1 0 2 0 0 0 0]
 [0 0 1 0 0 0 1 0 0 0]
 [0 1 0 0 0 0 0 1 0 0]
 [1 0 0 0 0 0 0 0 1 0]
 [2 2 2 1 1 1 0 0 0 0]]
Antalet farliga positioner är: 12


## Lucka 6
### Del 1


In [101]:
#Långsam och minneskrävande lösning :(

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80

alla_fiskar = np.array(eval(läsin_fil(sökväg)[0]))

for i in range(antal_dagar):
    #print(i)
    alla_fiskar -= 1
    nya_fiskar = np.where(alla_fiskar == -1)[0]
    
    alla_fiskar[nya_fiskar] = 6
    alla_fiskar = np.append(alla_fiskar, [8 for _ in range(nya_fiskar.size)])

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.size} st.")

Antalet fiskar efter 80 dagar är 5934 st.


### Del 2

In [103]:
# Betydligt effektivare lösning :D

sökväg = "files/exempel 6.txt"
#sökväg = "files/input 6.txt"

#antal_dagar = 18
antal_dagar = 80
#antal_dagar = 256

fiskar_vid_dag_0 = np.array(eval(läsin_fil(sökväg)[0]))
alla_fiskar = np.array([(fiskar_vid_dag_0 == i).sum()  for i in range (9)], np.int64)

for i in range(antal_dagar):

    alla_fiskar = np.roll(alla_fiskar, -1)
    alla_fiskar[6] += alla_fiskar[8]

print(f"Antalet fiskar efter {antal_dagar} dagar är {alla_fiskar.sum()} st.")

Antalet fiskar efter 80 dagar är 5934 st.


## Lucka 7
### Del 1


In [170]:
sökväg = "files/exempel 7.txt"
#sökväg = "files/input 7.txt"

krabbor_position = np.array(eval(läsin_fil(sökväg)[0]))
#krabbor_position.sort()
#krabbor_position.size
intervall_positioner = range(krabbor_position.min(), krabbor_position.max() + 1)

In [181]:

lägsta_bränsleförbrukning = min([np.absolute(krabbor_position - p).sum() for p in intervall_positioner])
print(f"Den lägta bränsleförbrukningen är {lägsta_bränsleförbrukning}")

Den lägta bränsleförbrukningen är 37


### Del 2

In [173]:
p = intervall_positioner[5]
[sum([ j for j in range(i + 1)]) for i in (np.absolute(krabbor_position - p))]

[66, 10, 6, 15, 1, 6, 3, 10, 6, 45]

In [179]:
lägsta_bränsleförbrukning = min([sum([sum([ j for j in range(i + 1)]) for i in (np.absolute(krabbor_position - p))]) for p in intervall_positioner])


print(f"Den position som ger lägst bränsleförbrukning är {position_lägst_bränsleförbrukning}")

Den position som ger minst bränsleförbrukning är 168


## Lucka 8
### Del 1


### Del 2

## Lucka 9
### Del 1


### Del 2

## Lucka 10
### Del 1


### Del 2

## Lucka 11
### Del 1


### Del 2

## Lucka 12
### Del 1


### Del 2

## Lucka 13
### Del 1


### Del 2

## Lucka 14
### Del 1


### Del 2

## Lucka 15
### Del 1


### Del 2

## Lucka 16
### Del 1


### Del 2

## Lucka 17
### Del 1


### Del 2

## Lucka 18
### Del 1


### Del 2

## Lucka 19
### Del 1


### Del 2

## Lucka 20
### Del 1


### Del 2

## Lucka 21
### Del 1


### Del 2

## Lucka 22
### Del 1


### Del 2

## Lucka 23
### Del 1


### Del 2

## Lucka 24
### Del 1


### Del 2

## Lucka 25
### Del 1


### Del 2